ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][SQL Server Native Client 11.0][SQL Server]Database 'amrutha_nov27_09' already exists. Choose a different database name. (1801) (SQLExecDirectW)")
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][SQL Server Native Client 11.0][SQL Server]Database 'amrutha_nov27_09' already exists. Choose a different database name. (1801) (SQLExecDirectW)")
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][SQL Server Native Client 11.0][SQL Server]Database 'amrutha_nov27_09' already exists. Choose a different database name. (1801) (SQLExecDirectW)")
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][SQL Server Native Client 11.0][SQL Server]Database 'amrutha_dec4_01' already exists. Choose a different database name. (1801) (SQLExecDirectW)")
ERROR:root:Error in script.py: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
ERROR:root:Error in script.py: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
ERROR:root:Error in script.py: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
ERROR:root:Error in script.py: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
ERROR:root:Error in script.py: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
ERROR:root:Error in script.py: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
ERROR:root:Error in script.py: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
ERROR:root:Error in script.py: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
ERROR:root:Error in script.py: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
ERROR:root:Error in script.py: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
ERROR:root:Error in script.py: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
ERROR:root:Error in script.py: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
ERROR:root:Error in script.py: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
ERROR:root:Error in script.py: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
ERROR:root:Error in script.py: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Database 'amrutha_dec22_05' already exists. Choose a different database name. (1801) (SQLExecDirectW)") 2023-12-22 14:57:53
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Database 'amrutha_dec22_05' already exists. Choose a different database name. (1801) (SQLExecDirectW)") 2023-12-22 14:59:46
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Database 'amrutha_dec22_05' already exists. Choose a different database name. (1801) (SQLExecDirectW)") 2023-12-22 15:07:16
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Database 'amrutha_dec22_05' already exists. Choose a different database name. (1801) (SQLExecDirectW)") 2023-12-22 19:18:54
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Database 'amrutha_dec22_09' already exists. Choose a different database name. (1801) (SQLExecDirectW)") 2023-12-22 20:15:45
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Database 'amrutha_dec22_09' already exists. Choose a different database name. (1801) (SQLExecDirectW)") 2023-12-22 20:18:44
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Database 'amrutha_dec22_09' already exists. Choose a different database name. (1801) (SQLExecDirectW)") 2023-12-22 20:27:21
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Database 'amrutha_dec26_02' already exists. Choose a different database name. (1801) (SQLExecDirectW)") 2023-12-26 14:15:20
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Database 'amrutha_dec26_02' already exists. Choose a different database name. (1801) (SQLExecDirectW)") 2023-12-26 14:18:29
ERROR:root:Error in script.py: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot drop database "amrutha_dec26_02" because it is currently in use. (3702) (SQLExecDirectW)') 2023-12-26 14:21:06
ERROR:root:Error in script.py: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot drop database "amrutha_dec26_02" because it is currently in use. (3702) (SQLExecDirectW)') 2023-12-26 14:22:11
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'DATABASE'. (102) (SQLExecDirectW)") 2023-12-27 12:12:57
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'DATABASE'. (102) (SQLExecDirectW)") 2023-12-27 12:13:24
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]CREATE DATABASE permission denied in database 'master'. (262) (SQLExecDirectW)") 2024-01-04 14:16:12
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]CREATE DATABASE permission denied in database 'master'. (262) (SQLExecDirectW)") 2024-01-04 14:17:12
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]CREATE DATABASE permission denied in database 'master'. (262) (SQLExecDirectW)") 2024-01-04 14:20:44
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]CREATE DATABASE permission denied in database 'master'. (262) (SQLExecDirectW)") 2024-01-04 14:35:03
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '3520031'. (102) (SQLExecDirectW)") 2024-01-05 12:44:22
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '3520031'. (102) (SQLExecDirectW)") 2024-01-05 12:45:51
ERROR:root:Error in script.py: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '3520031'. (102) (SQLExecDirectW)") 2024-01-05 12:46:09
ERROR:root:Error in script.py: Worksheet named 'Cable' not found 2024-01-05 12:47:22
ERROR:root:Error in script.py: Worksheet named 'Cable' not found 2024-01-05 12:51:22
ERROR:root:Error in script.py: Worksheet named 'Cable' not found 2024-01-05 12:53:15
ERROR:root:Error in script.py: Worksheet named 'Cable' not found 2024-01-05 12:57:00
ERROR:root:Error in script.py: Worksheet named 'Cable' not found 2024-01-05 13:01:03
ERROR:root:Error in script.py: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot drop database "amrutha_jan5_9" because it is currently in use. (3702) (SQLExecDirectW)') 2024-01-05 13:28:49
ERROR:root:Error in script.py: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot drop database "amrutha_jan5_9" because it is currently in use. (3702) (SQLExecDirectW)') 2024-01-05 13:29:09
ERROR:root:Error in script.py: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot drop database "amrutha_jan5_10" because it is currently in use. (3702) (SQLExecDirectW)') 2024-01-05 13:42:04
